package com.artproficiencyapp.extension


val PERMISSION_REQUEST_CODE = 1
val LOGIN = 2
var STATUS_CODE = 200
var MESSAGE = "message"
val FORGOTPASSWORD = 3
val DIRECTOR_SIGNUP = 4
val STUDENT_SIGNUP = 5
val GET_DIRECTORS = 6
val OTP_VERIFY = 7
val RESEND_OTP_VERIFY = 12
val LEVEL_MEMBER=8
val FINGER=9
val REPORT_AGENCY=10
val FACEBOOK_LOGIN=11
val STATUS=200
val GET_CATEGORIES_LIST =13
val GET_QUESTION=14
val STUDENT="STUDENT"
val DIRECTOR="DIRECTOR"